### ISSUE TITLE
Bug: `downloadManifest` doesn't actually download any manifests

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-edc/GradlePlugins#291]
## Expected behaviour

`downloadManifests` should iterate through all dependencies of the project it was called on, and download the autodoc manifest for that project dependency.

## Observed behaviour

the manifest file - if one exists - is not downloaded

## Possible cause
in `AbstractManifestResolveTask`, a filter is put on the stream of dependencies:
```java
                .filter(dep -> dep instanceof DefaultProjectDependency)
```
which may be the culprit, as autodoc manifests, that are resolved from Maven central, are of type `DefaultExternalModuleDependency`.

## Possible implementation

filter every dependency of every configuration for `DefaultExternalModuleDependency`, and attempt to resolve it appending the manifest classifier (`"manifest"`) and the manifest dependency type (`"json"`)

\cc @thomasrutger

**Comment by thomasrutger** [comment]
I can confirm that `.filter(dep -> dep instanceof DefaultProjectDependency)` indeed filters out the external manifests
