### ISSUE TITLE
Make `edc-build` plugin configure the `PublishingExtension` automatically

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-edc/GradlePlugins#58]
# Feature Request

Currently, everytime we want a module to be pushed we have to define a publication on its build file:
```kotlin
publishing {
    publications {
        create<MavenPublication>(project.name) {
            from(components["java"])
        }
    }
}
```

seems to be a lot of overhead to be put in every build file, but we could make the `edc-build` able to create a default publication with "java" component for all the subprojects with the `maven-publish` plugin loaded.

## Which Areas Would Be Affected?
build

## Why Is the Feature Desired?
cleanup

## Solution Proposal
-

## Type of Issue
-

## Checklist

- [x] assigned appropriate label?
- [x] **Do NOT select a milestone or an assignee!**

**Comment by paullatzelsperger** [comment]
I'm assigning this to @ronjaquensel as she expressed interest in getting involved with the gradle stuff.
